import"./modulepreload-polyfill-B5Qt9EMX.js";document.addEventListener("DOMContentLoaded",function(){const o=document.getElementById("clipButton"),d=document.getElementById("openSidepanelButton"),l=document.getElementById("status"),u=document.getElementById("statusIcon");if(!o||!d||!l||!u){console.error("Required DOM elements not found");return}const h={loading:document.createRange().createContextualFragment(`
      <svg class="animate-spin" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="12" cy="12" r="10" stroke-dasharray="32" stroke-dashoffset="16"></circle>
      </svg>
      Clipping...
    `),default:document.createRange().createContextualFragment(`
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"></path>
        <rect x="8" y="2" width="8" height="4" rx="1" ry="1"></rect>
      </svg>
      Clip Current Page
    `)};function i(e,t="ready"){requestAnimationFrame(()=>{l.textContent=e,u.className=`status-icon ${t}`})}function p(e){requestAnimationFrame(()=>{o.disabled=e,o.innerHTML="",o.appendChild(e?h.loading.cloneNode(!0):h.default.cloneNode(!0))})}o.addEventListener("click",async()=>{var e,t,a;try{p(!0),i("Clipping content...","ready");const[n]=await chrome.tabs.query({active:!0,currentWindow:!0});if(!(n!=null&&n.id))throw new Error("No active tab found");const r=await chrome.tabs.sendMessage(n.id,{type:"CLIP_CONTENT"});if(!r||!r.success)throw new Error((r==null?void 0:r.error)||"Failed to clip content");if(!((e=r.data)!=null&&e.raw_query)||!((t=r.data)!=null&&t.answer_markdown))throw new Error("Invalid content format");const c=await fetch("http://localhost:8000/queries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(r.data)});if(!c.ok){const w=await c.json();throw new Error(w.detail||"API request failed")}const s=await c.json();if(s.id&&s.sonar_status)i("Content clipped successfully!","ready"),s.sonar_status==="error"&&console.warn("Sonar processing failed:",(a=s.sonar_data)==null?void 0:a.error);else throw new Error("Invalid API response format")}catch(n){console.error("Error:",n),i(n instanceof Error?n.message:"Failed to clip content","error")}finally{p(!1)}}),d.addEventListener("click",async()=>{chrome.sidePanel?await chrome.sidePanel.open({windowId:chrome.windows.WINDOW_ID_CURRENT}):chrome.windows.create({url:"sidepanel.html",type:"popup",width:400,height:600})}),chrome.tabs.query({active:!0,currentWindow:!0},async e=>{var a;const t=(a=e[0])==null?void 0:a.url;t!=null&&t.includes("perplexity.ai")||(o.disabled=!0,i("Please navigate to Perplexity AI","error"))})});
//# sourceMappingURL=popup-D47h6ZhA.js.map
