name: Backend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/backend

    env:
      # Required for Sonar API integration
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      # Development database (SQLite)
      SQLALCHEMY_DATABASE_URL: "sqlite:///./test.db"
      # Python path for imports
      PYTHONPATH: ${{ github.workspace }}/packages/backend

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-asyncio
        
    - name: Run tests with coverage
      run: |
        python -m pytest tests/ --cov=app --cov-report=xml
        
    - name: Upload coverage to Codecov
      if: success() && github.event_name == 'push'
      uses: codecov/codecov-action@v3
      with:
        file: ./packages/backend/coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }} 