name: Chrome Extension Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'extension/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'extension/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd extension
        npm install
        
    - name: Lint extension
      run: |
        cd extension
        npm run lint || true  # Don't fail if linting is not set up
        
    - name: Verify extension files
      run: |
        cd extension
        test -f manifest.json
        test -f background.js
        test -f content-script.js
        test -f popup.html
        test -f popup.js 